config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create] do
  resources :bookmarks, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  # A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
  validates :movie_id, uniqueness: { scope: :list_id,
  message: "not unique movie, list combination" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  # When you delete a list, you should delete all associated bookmarks (but not the movies as they can be referenced in other lists).

  # A list must have a unique name.
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # You can’t delete a movie if it is referenced in at least one bookmark.

  # A movie must have a unique title.
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, except: :destroy

  def new
     @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

   def find_list
     @list = List.find(params[:list_id])
   end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit]

  def index
    @list = List.all
   end

   def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
   end

   def new
    @list = List.new
   end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  #  def edit
  #  end



  #  def update
  #   if @list.update(list_params)
  #      redirect_to @list, notice: 'List was successfully updated.'
  #    else
  #      render :edit
  #    end
  #  end


  #  def destroy
  #    @list.destroy
  #    redirect_to list_url, notice: 'List was successfully destroyed.'
  #  end

   private

   def set_list
     @list = List.find(params[:id])
   end

   def list_params
     params.require(:list).permit(:name)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, prompt: "Choose a Movie" %>
   <%= f.input :comment %>
   <%= f.submit class: 'btn btn-primary' %>

 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All lists</h1>
    <ul>
    <% @list.each do |list| %>
      <li>
        <%= link_to list.name, list_path(list) %>
      </li>
    <% end %>
    </ul>
 <%= link_to "Add a new List", new_list_path, class: 'btn btn-primary' %>

app/views/lists/new.html.erb
 <h1>Create a new list</h1>
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

app/views/lists/show.html.erb
<h1>List</h1>
<p><%= @list.name %> </p>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.movie.title %> - <%= link_to "delete", bookmark_path(bookmark), method: :delete %></li>
  <% end %>
</ul>
 <h2> <%= link_to "Return to lists", lists_path, class: 'btn btn-primary' %><h2>
 <h2> <%= link_to "Add a movie", new_list_bookmark_path(@list), class: 'btn btn-primary' %><h2>